const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        }, {
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 90,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 5,
            countInStock: 20,
            description: 'A simple shirt',
        }, {
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A good shirt',
        }, {
            name: 'Casual Pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 65,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        }, {
            name: 'Golf Pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 70,
            brand: 'Zara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        }, {
            name: 'Classic Pants',
            category: 'ShPantsirts',
            image: '/images/pants3.jpg',
            price: 72,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
    ],
};

export default data;